//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KKManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start application.
        /// </summary>
        public static string FailedToStartApplicationMessageTitle {
            get {
                return ResourceManager.GetString("FailedToStartApplicationMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create file in directory {0} because of a security issue - {1}
        ///
        ///Do you want KK Manager to attempt to fix the issue? Click cancel if you want to abort..
        /// </summary>
        public static string GetTempDownloadFilename_SecurityException_Message {
            get {
                return ResourceManager.GetString("GetTempDownloadFilename_SecurityException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s a newer version of KK Manager available. Mod updates will not work until you update.
        ///
        ///Do you want to open the download page of the latest version of KKManager?.
        /// </summary>
        public static string KKManagerOutdatedMessageBody {
            get {
                return ResourceManager.GetString("KKManagerOutdatedMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KK Manager is outdated.
        /// </summary>
        public static string KKManagerOutdatedMessageTitle {
            get {
                return ResourceManager.GetString("KKManagerOutdatedMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open the log file: {0}
        ///
        ///If the game doesn&apos;t seem to generate a log file, it might be generated somewhere inside appdata.
        ///
        ///Try setting &apos;redirectOutputLog=true&apos; in doorstop_config.ini, and if that doesn&apos;t result in a log file being created inside game root directory, enable disk log in BepInEx.cfg..
        /// </summary>
        public static string OpenGameLogFailedMessage {
            get {
                return ResourceManager.GetString("OpenGameLogFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open log file.
        /// </summary>
        public static string OpenGameLogMessageTitle {
            get {
                return ResourceManager.GetString("OpenGameLogMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of KKManager is available. Do you want to go to the download page?.
        /// </summary>
        public static string SelfUpdater_NewVersionMessage {
            get {
                return ResourceManager.GetString("SelfUpdater_NewVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version is available.
        /// </summary>
        public static string SelfUpdater_NewVersionTitle {
            get {
                return ResourceManager.GetString("SelfUpdater_NewVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
